name: unilink_flutter_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_sign_in: "^4.5.1"
  firebase_core: 1.7.0
  firebase_auth: 3.1.1
  dotted_border: ^2.0.0+1
  flutter_spinbox: ^0.6.0
  provider: 6.0.0
  http: 0.13.3
  badges: ^2.0.1
  carousel_slider: ^4.0.0
  fluttertoast: ^8.0.8
  flutter:
    sdk: flutter
  date_field: 2.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  # map screen
  dio: ^4.0.0
  flutter_polyline_points: ^0.2.6
  google_maps_flutter: ^2.0.2
  geolocator: ^5.1.5
  geocoder: any
  # spinner block ui
  flutter_spinkit: ^5.1.0

  group_radio_button: ^1.1.0
  flutter_staggered_grid_view: ^0.4.0
  agora_rtc_engine: 3.3.3
  permission_handler:
  localstorage: ^4.0.0+1
  zefyrka: ^1.0.10
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^5.0.0+4
  firebase_messaging: ^10.0.8
  firebase_analytics: ^8.3.3
  firebase_analytics_web: ^0.3.0+1
  image_picker: ^0.8.4+4
  socket_io_client: ^2.0.0-beta.1
  timeago: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/google-1.png
    - assets/icons/phone-1.png
    - assets/icons/avatar-long.jpg
    - assets/icons/avatar-tuan.jpg
    - assets/icons/avatar-tin.jpg
    - assets/icons/avatar-vinh.jpg
    - assets/icons/avatar-vinh.png
    - assets/icons/store-1.png
    - assets/icons/map-1.png
    - assets/icons/group-1.png
    - assets/icons/group-2.png
    - assets/icons/group-3.png
    - assets/icons/join-1.png
    - assets/icons/back.png
    - assets/icons/logo.png
    - assets/icons/tick.png
    - assets/icons/google-2.png
    - assets/icons/tim-nhom.png
    - assets/icons/profile-infor.png
    - assets/icons/invite.png
    - assets/icons/member_15px.png
    - assets/icons/skill_15px.png
    - assets/icons/location_15px.png
    - assets/icons/invite-1.png
    - assets/icons/mute-notify-1.png
    - assets/icons/note-1.png
    - assets/icons/notify-2.png
    - assets/icons/out-1.png
    - assets/icons/flus-icon.png
    - assets/icons/edit.png
    - assets/icons/avatar-group.png
    - assets/icons/edit.png
    - assets/icons/avatar-group.png
    - assets/icons/name-30px.png
    - assets/icons/DOB-30px.png
    - assets/icons/gender-30px.png
    - assets/icons/location-30px.png
    - assets/icons/major-30px.png
    - assets/icons/skill-30px.png
    - assets/icons/university-30px.png
    - assets/icons/flus.png
    - assets/icons/distance.png
    - assets/icons/people_image.png
    - assets/icons/group_image.png
    - assets/icons/video-call.png
    - assets/icons/call.png
    - assets/icons/setting.png
    - assets/icons/ask-anwer.png
    - assets/icons/post.png
    - assets/icons/3-dot.png
    - assets/icons/comment.png
    - assets/icons/question-answer.png
    - assets/icons/question-image.png
    - assets/icons/accept-call.png
    - assets/icons/refuse-call.png
    - assets/icons/voice-mute.png
    - assets/icons/chatbox.png
    - assets/icons/rejected-calls.png
    - assets/icons/list.png
    - assets/icons/create-new.png
    - assets/icons/x-icon.png
    - assets/icons/invite-2.png
    - assets/icons/delete.png
    - assets/icons/user-1.png
    - assets/icons/chat-1.png
    - assets/icons/video-1.png
    - assets/icons/handshake.png
    - assets/icons/invite-3.png
    - assets/icons/group-4.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
